name: Build

on:
  push:
    tags:
      - v[0-9]+.*

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Build and upload Rust binary to GitHub Releases
        uses: taiki-e/upload-rust-binary-action@v1.18.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          filename: target/release/gpu_auto_top
          tag: ${{ github.ref }}